### ISSUE TITLE
This is not valid Move

### ISSUE THREAD

**Issue by damirka** [0xNeit/sui-nouns#1]
Hey @0xNeit, I wanted to contribute and help migrate the codebase to Move 2024, however, what I saw in the repo is not valid Move. Can you please explain the intention and what you're trying to achieve? Perhaps, I could help you shape it into something?

**Comment by 0xNeit** [comment]
I was basically trying to re-implement NounsDAO in Sui Move. I have not had time to actually do it because of my busy schedule. But i don't mind picking it up again, now that i know that someone is interested.

I can rewrite the bits of solidity code still present in the code base if you want

**Comment by 0xNeit** [comment]
Update: I have migrated the codebase to Move 2024 and also rewritten all solidity code in Move
